version: '3.8'

services:
  # Base de datos PostgreSQL
  db:
    image: postgis/postgis:15-3.3-alpine
    #image: postgres:15-alpine
    container_name: django_postgres
    ports:
        - "5432:5432"
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - django-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Aplicación Django
  web:
    build: ./app
    container_name: django_web
    restart: unless-stopped
    volumes:
      - ./app:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    environment:
      - DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - django-network

  # Servidor web Nginx
  nginx:
    build: ./nginx
    container_name: django_nginx
    restart: unless-stopped
    ports:

      - "80:80"
      - "443:443"

    volumes:
      - static_volume:/app/staticfiles:ro
      - media_volume:/app/mediafiles:ro
      - ./ssl:/etc/nginx/ssl:ro
      - ./frontend:/app/frontend
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro

    depends_on:
      - web
    networks:
      - django-network

  # servicio pgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: django_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: jherenu@gmail.com
      PGADMIN_DEFAULT_PASSWORD: juaniT01603
    ports:
      - "5050:80"
    networks:
      - django-network



volumes:
  static_volume:
  media_volume:

networks:
  django-network:
    driver: bridge

