# Generated by Django 5.2.7 on 2025-10-18 18:53

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


def update_content_type(apps, schema_editor):
    """Actualizar ContentType de gps.movil a moviles.movil"""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        ct = ContentType.objects.get(app_label='gps', model='movil')
        ct.app_label = 'moviles'
        ct.save()
        print("✓ ContentType actualizado: gps.movil → moviles.movil")
    except ContentType.DoesNotExist:
        print("⚠ ContentType gps.movil no existe")


def revert_content_type(apps, schema_editor):
    """Revertir ContentType de moviles.movil a gps.movil"""
    ContentType = apps.get_model('contenttypes', 'ContentType')
    
    try:
        ct = ContentType.objects.get(app_label='moviles', model='movil')
        ct.app_label = 'gps'
        ct.save()
        print("✓ ContentType revertido: moviles.movil → gps.movil")
    except ContentType.DoesNotExist:
        print("⚠ ContentType moviles.movil no existe")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gps', '0004_add_equipo_gps_fk'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Movil',
                    fields=[
                        ('id', models.BigAutoField(primary_key=True, serialize=False)),
                        ('codigo', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                        ('alias', models.CharField(blank=True, max_length=100, null=True)),
                        ('patente', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                        ('vin', models.CharField(blank=True, max_length=17, null=True)),
                        ('marca', models.TextField(blank=True, null=True)),
                        ('modelo', models.TextField(blank=True, null=True)),
                        ('anio', models.SmallIntegerField(blank=True, null=True)),
                        ('color', models.TextField(blank=True, null=True)),
                        ('tipo_vehiculo', models.CharField(blank=True, max_length=20, null=True)),
                        ('gps_id', models.CharField(blank=True, db_column='gps_id', help_text='DEPRECATED - Usar equipo_gps', max_length=50, null=True, unique=True)),
                        ('ultimo_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ('ultimo_lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                        ('ultimo_rumbo', models.SmallIntegerField(blank=True, null=True)),
                        ('ultima_velocidad_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                        ('ultima_altitud_m', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                        ('ult_satelites', models.SmallIntegerField(blank=True, null=True)),
                        ('ultimo_hdop', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                        ('fecha_gps', models.DateTimeField(blank=True, null=True)),
                        ('fecha_recepcion', models.DateTimeField(blank=True, null=True)),
                        ('raw_data', models.TextField(blank=True, null=True)),
                        ('raw_json', models.JSONField(blank=True, null=True)),
                        ('ignicion', models.BooleanField(blank=True, null=True)),
                        ('bateria_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                        ('odometro_km', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                        ('km_calculado', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                        ('km_ultimo_calculo_at', models.DateTimeField(blank=True, null=True)),
                        ('dir_formateada', models.TextField(blank=True, null=True)),
                        ('dir_calle', models.TextField(blank=True, null=True)),
                        ('dir_numero', models.TextField(blank=True, null=True)),
                        ('dir_piso', models.TextField(blank=True, null=True)),
                        ('dir_depto', models.TextField(blank=True, null=True)),
                        ('dir_barrio', models.TextField(blank=True, null=True)),
                        ('dir_localidad', models.TextField(blank=True, null=True)),
                        ('dir_municipio', models.TextField(blank=True, null=True)),
                        ('dir_provincia', models.TextField(blank=True, null=True)),
                        ('dir_cp', models.TextField(blank=True, null=True)),
                        ('dir_pais', models.TextField(blank=True, default='Argentina', null=True)),
                        ('geo_fuente', models.CharField(blank=True, max_length=30, null=True)),
                        ('geo_confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                        ('geo_actualizado_at', models.DateTimeField(blank=True, null=True)),
                        ('geo_geohash', models.CharField(blank=True, max_length=15, null=True)),
                        ('geom', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                        ('icono_tipo', models.CharField(blank=True, max_length=20, null=True)),
                        ('icono_color_hex', models.CharField(blank=True, max_length=7, null=True)),
                        ('icono_url', models.TextField(blank=True, null=True)),
                        ('icono_rotacion_modo', models.CharField(blank=True, max_length=10, null=True)),
                        ('icono_rotacion_grados', models.SmallIntegerField(blank=True, null=True)),
                        ('icono_escala', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                        ('activo', models.BooleanField(default=True)),
                        ('created_at', models.DateTimeField(auto_now_add=True)),
                        ('updated_at', models.DateTimeField(auto_now=True)),
                        ('equipo_gps', models.ForeignKey(blank=True, db_column='equipo_gps_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moviles', to='gps.Equipo', verbose_name='Equipo GPS')),
                    ],
                    options={
                        'verbose_name': 'Móvil',
                        'verbose_name_plural': 'Móviles',
                        'db_table': 'moviles',
                    },
                ),
            ],
            database_operations=[
                # NO hacer nada en BD - tabla ya existe
            ],
        ),
        
        migrations.RunPython(
            code=update_content_type,
            reverse_code=revert_content_type,
        ),
    ]