# Generated by Django - Squashed migration
from django.db import migrations, models
import django.contrib.gis.db.models.fields
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [

    ]

    initial = True

    dependencies = [
        ('gps', '0005_empresa_equipo_delete_movil'),
    ]

    operations = [
        # Esta migración no hace nada en la BD
        # Solo registra el estado final de los modelos
    ]