# Generated by Django 5.2.7 on 2025-10-20 14:10

import django.db.models.deletion
from django.db import migrations, models


def copiar_datos_geocode(apps, schema_editor):
    """
    Copiar datos de geocodificación de moviles a moviles_geocode
    """
    Movil = apps.get_model('moviles', 'Movil')
    MovilGeocode = apps.get_model('moviles', 'MovilGeocode')
    
    # Obtener todos los móviles
    moviles = Movil.objects.all()
    
    # Crear geocodificación para cada móvil
    geocodes = []
    for movil in moviles:
        geocodes.append(MovilGeocode(
            movil_id=movil.id,
            dir_formateada=movil.dir_formateada,
            dir_calle=movil.dir_calle,
            dir_numero=movil.dir_numero,
            dir_piso=movil.dir_piso,
            dir_depto=movil.dir_depto,
            dir_barrio=movil.dir_barrio,
            dir_localidad=movil.dir_localidad,
            dir_municipio=movil.dir_municipio,
            dir_provincia=movil.dir_provincia,
            dir_cp=movil.dir_cp,
            dir_pais=movil.dir_pais,
            geo_fuente=movil.geo_fuente,
            geo_confianza=movil.geo_confianza,
            geo_actualizado_at=movil.geo_actualizado_at,
            geo_geohash=movil.geo_geohash,
        ))
    
    # Crear en bulk para mejor performance
    if geocodes:
        MovilGeocode.objects.bulk_create(geocodes)
        print(f"✅ Copiados {len(geocodes)} registros de geocodificación")


def reversar_copia_datos(apps, schema_editor):
    """
    Operación inversa: eliminar todos los geocodes
    """
    MovilGeocode = apps.get_model('moviles', 'MovilGeocode')
    count = MovilGeocode.objects.count()
    MovilGeocode.objects.all().delete()
    print(f"✅ Eliminados {count} registros de geocodificación")


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0001_initial'),
    ]

    operations = [
        # 1. Crear tabla moviles_geocode
        migrations.CreateModel(
            name='MovilGeocode',
            fields=[
                ('movil', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE,
                    primary_key=True,
                    related_name='geocode',
                    serialize=False,
                    to='moviles.movil',
                    verbose_name='Móvil'
                )),
                ('dir_formateada', models.TextField(blank=True, null=True, verbose_name='Dirección Formateada')),
                ('dir_calle', models.TextField(blank=True, null=True, verbose_name='Calle')),
                ('dir_numero', models.TextField(blank=True, null=True, verbose_name='Número')),
                ('dir_piso', models.TextField(blank=True, null=True, verbose_name='Piso')),
                ('dir_depto', models.TextField(blank=True, null=True, verbose_name='Departamento')),
                ('dir_barrio', models.TextField(blank=True, null=True, verbose_name='Barrio')),
                ('dir_localidad', models.TextField(blank=True, null=True, verbose_name='Localidad')),
                ('dir_municipio', models.TextField(blank=True, null=True, verbose_name='Municipio')),
                ('dir_provincia', models.TextField(blank=True, null=True, verbose_name='Provincia')),
                ('dir_cp', models.TextField(blank=True, null=True, verbose_name='Código Postal')),
                ('dir_pais', models.TextField(blank=True, default='Argentina', null=True, verbose_name='País')),
                ('geo_fuente', models.CharField(blank=True, max_length=30, null=True, verbose_name='Fuente Geocodificación')),
                ('geo_confianza', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Confianza (%)')),
                ('geo_actualizado_at', models.DateTimeField(blank=True, null=True, verbose_name='Última Actualización')),
                ('geo_geohash', models.CharField(blank=True, max_length=15, null=True, verbose_name='Geohash')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Actualización')),
            ],
            options={
                'verbose_name': 'Geocodificación de Móvil',
                'verbose_name_plural': 'Geocodificaciones de Móviles',
                'db_table': 'moviles_geocode',
            },
        ),
        
        # 2. Copiar datos de moviles a moviles_geocode
        migrations.RunPython(
            copiar_datos_geocode,
            reversar_copia_datos
        ),
        
        # 3. Eliminar campos de moviles
        migrations.RemoveField(model_name='movil', name='dir_barrio'),
        migrations.RemoveField(model_name='movil', name='dir_calle'),
        migrations.RemoveField(model_name='movil', name='dir_cp'),
        migrations.RemoveField(model_name='movil', name='dir_depto'),
        migrations.RemoveField(model_name='movil', name='dir_formateada'),
        migrations.RemoveField(model_name='movil', name='dir_localidad'),
        migrations.RemoveField(model_name='movil', name='dir_municipio'),
        migrations.RemoveField(model_name='movil', name='dir_numero'),
        migrations.RemoveField(model_name='movil', name='dir_pais'),
        migrations.RemoveField(model_name='movil', name='dir_piso'),
        migrations.RemoveField(model_name='movil', name='dir_provincia'),
        migrations.RemoveField(model_name='movil', name='geo_actualizado_at'),
        migrations.RemoveField(model_name='movil', name='geo_confianza'),
        migrations.RemoveField(model_name='movil', name='geo_fuente'),
        migrations.RemoveField(model_name='movil', name='geo_geohash'),
    ]