# Generated by Django 5.2.7 on 2025-10-23 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moviles', '0003_moviltelemetria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movil',
            name='bateria_pct',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='ignicion',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='km_calculado',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='km_ultimo_calculo_at',
        ),
        migrations.RemoveField(
            model_name='movil',
            name='odometro_km',
        ),
    ]
