# Generated by Django 5.2.7 on 2025-10-18 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gps', '0004_add_equipo_gps_fk'),
        ('moviles', '0001_squashed'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Movil',
                ),
            ],
            database_operations=[
                # NO hacer nada en BD - tabla la maneja moviles/ ahora
            ],
        ),
    ]